stages:
  - build
  - test
  - deploy

build-staging:
  stage: build
  script:
    - echo "Inciando a build do projeto:"
    - npm install
    - npm run build

test-staging:
  stage: test
  script:
    - echo "Build feita com sucesso. Inciando testes:"
    - npm install
    - npm run test

deploy-staging:
  stage: deploy
  script:
    - echo "Testes finalizados com sucesso. Iniciando deploy:"
    - firebase deploy --only hosting
