image: node:latest

stages:
  - build
  - test
  - deploy

build-staging:
  stage: build
  script:
    - npm ci
    - npm run build

test-staging:
  stage: test
  script:
    - npm ci
    - npm run test
