stages:
  - build
  - test
  - deploy

build-staging:
  stage: build
  script:
    - npm ci
    - npm run build

test-staging:
  stage: test
  script:
    - npm ci
    - npm run test

deploy-staging:
  stage: deploy
  script:
    - npm ci
    - npm i -g firebase-tools
    - firebase deploy --token $FIREBASE_TOKEN
