stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

build-staging:
  stage: build
  script:
    - npm ci
    - npm run build

test-staging:
  stage: test
  script:
    - npm ci
    - npm run test

deploy-staging:
  stage: deploy
  script:
    - npm ci
    - firebase deploy --only hosting --token $FIREBASE_TOKEN
